CREATE TABLE [dbo].[MedicalClaims_Base] (
    [ID]                  INT            IDENTITY (1, 1) NOT NULL,
    [ClientId]            INT            NULL,
    [ClaimNumber]         VARCHAR (100)  NULL,
    [ClaimSequence]       VARCHAR (100)  NULL,
    [YrMth]               CHAR (6)       NULL,
    [PriMemberID]         VARCHAR (100)  NULL,
    [MemberID]            VARCHAR (100)  NULL,
    [AltMemberID]         VARCHAR (100)  NULL,
    [MemberState]         VARCHAR (2)    NULL,
    [MemberZip]           VARCHAR (25)   NULL,
    [MemberRelationship]  VARCHAR (5)    NULL,
    [MemberDOB]           DATE           NULL,
    [MemberGender]        VARCHAR (5)    NULL,
    [MemberNbr]           VARCHAR (3)    NULL,
    [RecSource]           VARCHAR (100)  NULL,
    [RecType]             VARCHAR (5)    NULL,
    [PlanType]            VARCHAR (25)   NULL,
    [PlanGroupID]         VARCHAR (25)   NULL,
    [PlanGroup]           VARCHAR (25)   NULL,
    [ProviderId]          VARCHAR (100)  NULL,
    [ProviderState]       VARCHAR (2)    NULL,
    [ProviderZip]         VARCHAR (10)   NULL,
    [ProviderSpec]        VARCHAR (50)   NULL,
    [ProviderType]        VARCHAR (50)   NULL,
    [BillingProviderId]   VARCHAR (100)  NULL,
    [BillingProviderType] VARCHAR (50)   NULL,
    [TypeOfBill]          VARCHAR (10)   NULL,
    [TypeOfService]       VARCHAR (10)   NULL,
    [PlaceOfService]      VARCHAR (3)    NULL,
    [RevenueCode]         VARCHAR (10)   NULL,
    [BillingCode]         VARCHAR (10)   NULL,
    [ICD1]                VARCHAR (10)   NULL,
    [ICD2]                VARCHAR (10)   NULL,
    [ICD3]                VARCHAR (10)   NULL,
    [ICD4]                VARCHAR (10)   NULL,
    [ICD5]                VARCHAR (10)   NULL,
    [ICD6]                VARCHAR (10)   NULL,
    [ICD7]                VARCHAR (10)   NULL,
    [ICD8]                VARCHAR (10)   NULL,
    [ICD9]                VARCHAR (10)   NULL,
    [ICD10]               VARCHAR (10)   NULL,
    [Procedure1]          VARCHAR (10)   NULL,
    [Modifier1a]          VARCHAR (10)   NULL,
    [Modifier1b]          VARCHAR (10)   NULL,
    [ProcedureType1]      VARCHAR (10)   NULL,
    [Procedure2]          VARCHAR (10)   NULL,
    [Modifier2a]          VARCHAR (10)   NULL,
    [Modifier2b]          VARCHAR (10)   NULL,
    [ProcedureType2]      VARCHAR (10)   NULL,
    [Unit]                DECIMAL (7, 2) NULL,
    [DRG_Cde]             VARCHAR (15)   NULL,
    [MSDRG_Cde]           VARCHAR (15)   NULL,
    [MDG]                 VARCHAR (3)    NULL,
    [FromServiceDate]     DATE           NULL,
    [ToServiceDate]       DATE           NULL,
    [ServiceDays]         INT            NULL,
    [AdmitDate]           DATE           NULL,
    [DischargeDate]       DATE           NULL,
    [DischargeStatusCode] VARCHAR (100)  NULL,
    [PrimaryPayerFlag]    VARCHAR (10)   NULL,
    [InNetwork]           VARCHAR (5)    NULL,
    [MDCR_Ind]            VARCHAR (5)    NULL,
    [PCP]                 VARCHAR (5)    NULL,
    [SubmittedDate]       DATE           NULL,
    [PaidDate]            DATE           NULL,
    [ClaimStatusCode]     VARCHAR (5)    NULL,
    [ClaimStatus]         VARCHAR (100)  NULL,
    [BillAmt]             MONEY          NULL,
    [DedAmt]              MONEY          NULL,
    [CoPayAmt]            MONEY          NULL,
    [CoInsurance]         MONEY          NULL,
    [PaidAmt]             MONEY          NULL,
    [COBAmt]              MONEY          NULL,
    [TotalAmt]            MONEY          NULL,
    [Srv_Cnt]             MONEY          NULL,
    [Adj_Cde]             VARCHAR (15)   NULL,
    [Udef1]               VARCHAR (100)  NULL,
    [Udef2]               VARCHAR (100)  NULL,
    [Udef3]               VARCHAR (100)  NULL,
    [Udef4]               VARCHAR (100)  NULL,
    [ClassifierUSPM]      VARCHAR (4)    NULL,
    [H_HL_Category]       VARCHAR (50)   NULL,
    [H_ML_Category]       VARCHAR (50)   NULL,
    [H_Subcategory]       VARCHAR (50)   NULL,
    [css_diag_id]         VARCHAR (50)   NULL,
    [csc_proc_id]         VARCHAR (50)   NULL,
    [altClassifier]       VARCHAR (25)   NULL,
    [EpisodeID]           VARCHAR (10)   NULL,
    [EpisodeCode]         VARCHAR (50)   NULL,
    [CreatedBy]           VARCHAR (100)  NULL,
    [CreatedDate]         DATETIME       NULL,
    [LastUpdated]         DATETIME       NULL,
    [LastClaimFile]       VARCHAR (100)  NULL
);

