CREATE TABLE [dbo].[MemberProfile_Core]
 (
    [ID]                     INT           IDENTITY (1, 1) NOT NULL,
    [ClientId]               INT           NULL,
    [MemProfileType]         VARCHAR (10)  NULL,
    [SubscriberID]           VARCHAR (50)  NULL,
    [SubscriberSSN]          VARCHAR (12)  NULL,
    [PriMemberNbr]           VARCHAR (5)   NULL,
    [SubscriberAltID]        VARCHAR (50)  NULL,
    [MemberID]               VARCHAR (50)  NULL,
    [MemberSSN]              VARCHAR (12)  NULL,
	[MemberAltID]			 VARCHAR (50)  NULL,
    [IDSource]               VARCHAR (15)  NULL,
    [MemberRelationship]     VARCHAR (25)  NULL,
    [MemberRelationshipOrig] VARCHAR (25)  NULL,
    [FirstName]              VARCHAR (35)  NULL,
    [LastName]               VARCHAR (35)  NULL,
    [MiddleName]             VARCHAR (35)  NULL,
    [MemberDOB]              DATE          NULL,
    [MemberDOBYr]              TINYINT       NULL,
    [MemberGender]           CHAR (1)      NULL,
    [Address]                VARCHAR (100) NULL,
    [City]                   VARCHAR (35)  NULL,
    [State]                  VARCHAR (2)   NULL,
    [Zip]                    VARCHAR (14)  NULL,
    [Custom1]                VARCHAR (100) NULL,
    [Custom1_lbl]            VARCHAR (25)  NULL,
    [Custom2]                VARCHAR (100) NULL,
    [Custom2_lbl]            VARCHAR (25)  NULL,
    [Custom3]                VARCHAR (100) NULL,
    [Custom3_lbl]            VARCHAR (25)  NULL,
    [StartDte]               DATE          NULL,
    [EndDte]                 DATE          NULL,
    [Current]                BIT           NULL,
	[Order]					 SMALLINT	   NULL,
    [originalfiledate]       DATE          NULL,
    [lastfiledate]           DATE          NULL,
    [CreatedOn]              DATE          NULL,
    [LastUpdatedOn]          DATE          NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 100)
);

