CREATE TABLE [dbo].[MemberProfile_Base] (
    [ID]                     INT           IDENTITY (1, 1) NOT NULL,
    [ClientId]               INT           NULL,
    [YrMth]                  CHAR (6)      NULL,
    [MemProfileType]         VARCHAR (10)  NULL,
    [PriMemberID]            VARCHAR (50)  NULL,
    [PriSSN]                 VARCHAR (12)  NULL,
    [PriMemberNbr]           VARCHAR (5)   NULL,
    [AltID]                  VARCHAR (50)  NULL,
    [MemberID]               VARCHAR (50)  NULL,
    [MemberSSN]              VARCHAR (12)  NULL,
    [IDSource]               VARCHAR (15)  NULL,
    [MemberRelationship]     VARCHAR (25)  NULL,
    [MemberRelationshipOrig] VARCHAR (25)  NULL,
    [FirstName]              VARCHAR (35)  NULL,
    [LastName]               VARCHAR (35)  NULL,
    [MiddleName]             VARCHAR (35)  NULL,
    [MemberDOB]              DATE          NULL,
    [MemberAge]              TINYINT       NULL,
    [MemberAgeGrp]           VARCHAR (10)  NULL,
    [MemberGender]           CHAR (1)      NULL,
    [Address]                VARCHAR (100) NULL,
    [City]                   VARCHAR (35)  NULL,
    [State]                  VARCHAR (2)   NULL,
    [Zip]                    VARCHAR (14)  NULL,
    [Phone]                  VARCHAR (25)  NULL,
    [PlanID]                 VARCHAR (100) NULL,
    [PlanType]               VARCHAR (25)  NULL,
    [PlanGroupID]            VARCHAR (25)  NULL,
    [PlanGroup]              VARCHAR (25)  NULL,
    [CostCenter]             VARCHAR (50)  NULL,
    [MemberGroup]            VARCHAR (50)  NULL,
    [DepLoc]                 VARCHAR (50)  NULL,
    [Custom1]                VARCHAR (100) NULL,
    [Custom1_lbl]            VARCHAR (25)  NULL,
    [Custom2]                VARCHAR (100) NULL,
    [Custom2_lbl]            VARCHAR (25)  NULL,
    [Custom3]                VARCHAR (100) NULL,
    [Custom3_lbl]            VARCHAR (25)  NULL,
    [Custom4]                VARCHAR (100) NULL,
    [Custom4_lbl]            VARCHAR (25)  NULL,
    [Custom5]                VARCHAR (100) NULL,
    [Custom5_lbl]            VARCHAR (25)  NULL,
    [AsOfDate]               DATE          NULL,
    [StartDte]               DATE          NULL,
    [EndDte]                 DATE          NULL,
    [Current]                BIT           NULL,
    [originalfiledate]       DATE          NULL,
    [lastfiledate]           DATE          NULL,
    [CreatedOn]              DATE          NULL,
    [LastUpdatedOn]          DATE          NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 100)
);

