CREATE TABLE [dbo].[PharmClaims_Base] (
    [ID]                  INT            IDENTITY (1, 1) NOT NULL,
    [ClientId]            INT            NULL,
    [ClaimNumber]         VARCHAR (100)  NULL,
    [ClaimSequence]       VARCHAR (100)  NULL,
    [YrMth]               CHAR (6)       NULL,
    [PriMemberID]         VARCHAR (100)  NULL,
    [MemberID]            VARCHAR (100)  NULL,
    [AltMemberID]         VARCHAR (100)  NULL,
    [MemberState]         VARCHAR (2)    NULL,
    [MemberZip]           VARCHAR (25)   NULL,
    [MemberRelationship]  VARCHAR (5)    NULL,
    [MemberDOB]           DATE           NULL,
    [MemberGender]        VARCHAR (5)    NULL,
    [MemberNbr]           VARCHAR (3)    NULL,
    [RecSource]           VARCHAR (100)  NULL,
    [RecType]             VARCHAR (5)    NULL,
    [PlanType]            VARCHAR (25)   NULL,
    [PlanGroupID]         VARCHAR (25)   NULL,
    [PlanGroup]           VARCHAR (25)   NULL,
    [PrescriberID]        VARCHAR (100)  NULL,
    [PharmacyID]          VARCHAR (100)  NULL,
    [PharmacyName]        VARCHAR (150)  NULL,
    [PharmacyState]       VARCHAR (2)    NULL,
    [PharmacyZipCode]     VARCHAR (10)   NULL,
    [PharmacyType]        VARCHAR (25)   NULL,
    [NDC]                 VARCHAR (15)   NULL,
    [DrugName]            VARCHAR (100)  NULL,
    [DispensedQuantity]   DECIMAL (7, 2) NULL,
    [DaysSupply]          DECIMAL (7, 2) NULL,
    [GenericIndic]        VARCHAR (3)    NULL,
    [CompondIndic]        VARCHAR (10)   NULL,
    [MaintenanceDrug]     VARCHAR (5)    NULL,
    [FormularyStatus]     VARCHAR (10)   NULL,
    [DAW]                 VARCHAR (10)   NULL,
    [ServiceTypeID]       VARCHAR (5)    NULL,
    [ServiceType]         VARCHAR (50)   NULL,
    [DiagnosisCde]        VARCHAR (10)   NULL,
    [PrimaryCondition]    VARCHAR (50)   NULL,
    [WrittenDte]          DATE           NULL,
    [FilledDte]           DATE           NULL,
    [PaidDte]             DATE           NULL,
    [BilledAmt]           MONEY          NULL,
    [CoPayAmt]            MONEY          NULL,
    [DeductableAmt]       MONEY          NULL,
    [PaidAmt]             MONEY          NULL,
    [TotalPaidAll]        MONEY          NULL,
    [UsualCustAmt]        MONEY          NULL,
    [IngredCostAmt]       MONEY          NULL,
    [DispCostAmt]         MONEY          NULL,
    [SalesTaxAmt]         MONEY          NULL,
    [Conditions]          VARCHAR (2500) NULL,
    [DrugTypeCde]         VARCHAR (10)   NULL,
    [DrugType]            VARCHAR (100)  NULL,
    [DrugTypeSource]      VARCHAR (50)   NULL,
    [DrugCatCde]          VARCHAR (10)   NULL,
    [DruCat]              VARCHAR (100)  NULL,
    [DrugCatSource]       VARCHAR (50)   NULL,
    [TherapeuticClassCde] VARCHAR (10)   NULL,
    [TherapeuticClass]    VARCHAR (50)   NULL,
    [TherapeuticClassSub] VARCHAR (50)   NULL,
    [Status_Cde]          VARCHAR (5)    NULL,
    [CreatedDte]          DATETIME       NULL,
    [SourceFile]          VARCHAR (100)  NULL
);

